// @vitest-environment node
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createArtifactCache } from "./artifact-cache";

let data: string;
beforeEach(async () => { data = await fs.mkdtemp(path.join(os.tmpdir(), "spark-artifact-cache-")); });
afterEach(async () => { await fs.rm(data, { recursive: true, force: true }); });

describe("artifact cache", () => {
  it("reuses generated bytes and separates keys", async () => {
    const cache = createArtifactCache(data, "converted");
    let generated = 0;
    const generate = async () => { generated += 1; return Buffer.from("PDF"); };
    await expect(cache.get("key-a", generate)).resolves.toEqual(Buffer.from("PDF"));
    await expect(cache.get("key-a", generate)).resolves.toEqual(Buffer.from("PDF"));
    await expect(cache.get("key-b", generate)).resolves.toEqual(Buffer.from("PDF"));
    expect(generated).toBe(2);
  });
});
